import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { images } from '@/next.config'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>X formally known as Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/fav icon.jpeg" />
      </Head>

      <main className={`${styles.main}`}>
        <div className={styles.xLogo}>
          <Image src='/images/twitterlogo.webp' alt='Logo' width={850} height={550}/>
          </div>
          
        <div className={`${styles.body}`}>
          <h1 className={`${styles.h1}`}> Happening now</h1>
          <br></br>
          <h2 className={`${styles.h2}`}> Join Twitter today.</h2>
          <br></br>

          <button className={`${styles.googlebutton}`}>
            <Image className={`${styles.googlelogo}`} src={'/images/googlelogo.png'} alt="logo" width={40} height={30}></Image> 
            Sign in with Google 
          </button>

          <br></br>

          <button className={`${styles.applebutton}`}>
            <Image className={`${styles.applelogo}`} src={'/images/applelogo.svg'} alt="logo" width={30} height={40}></Image>
            Sign in with Apple
          </button>
          
          <p className={`${styles.or}`}> ━━━━━━━━ or ━━━━━━━━━</p>
          <button className={`${styles.createbutton}`}> Create Account</button>
          <br></br>
          <p className={`${styles.terms}`}> By signing up, you agree to the Terms of Service and <br></br>Privacy Policy, including Cookie Use <a href="#">Terms of conditions</a></p>
          <br></br>
          <br></br>
          <h3 className={`${styles.h3}`}> Already have an account?</h3>
          <br></br>
          <button className={`${styles.signinbutton}`}> Sign in</button>


        </div>
      </main>
    </>
  )
}
